<Project DefaultTarget="Build" Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.Engine.Lusas</RootNamespace>
    <OutputPath>..\Build\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>true</Optimize>
    <Configurations>Debug;Debug17;Debug18;Debug19;Debug191;Debug200;Debug210;Debug211;Debug220;Debug230;Release;Release17;Release18;Release19;Release191;Release200;Release210;Release211;Release220;Release230</Configurations>
    <AssemblyTitle>Lusas_Engine</AssemblyTitle>
    <Description>https://github.com/BHoM/Lusas_Toolkit</Description>
    <Product>Lusas_Engine</Product>
    <Copyright>Copyright © https://github.com/BHoM</Copyright>
    <AssemblyVersion>9.0.0.0</AssemblyVersion>
    <FileVersion>9.1.0.0</FileVersion>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;C:\ProgramData\BHoM\Assemblies&quot; /Y" />
  </Target>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug19|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release19|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug191|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release191|AnyCPU' ">
    <OutputPath>..\Build\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug200|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release200|AnyCPU'">
    <OutputPath>..\Build\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug210|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release210|AnyCPU'">
    <OutputPath>..\Build\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug211|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release211|AnyCPU'">
    <OutputPath>..\Build\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug220|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release220|AnyCPU'">
    <OutputPath>..\Build\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug230|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Build\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release230|AnyCPU'">
    <OutputPath>..\Build\</OutputPath>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Analytical_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Analytical_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Analytical_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Analytical_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Adapter">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Adapter.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Dimensional_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Dimensional_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Geometry_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Geometry_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Geometry_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Geometry_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Physical_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Physical_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Spatial_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Spatial_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Structure_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Structure_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Structure_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Structure_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lusas_oM\Lusas_oM.csproj" />
  </ItemGroup>
</Project>
