/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2020, the respective contributors. All rights reserved.
 *
 * Each contributor holds copyright over their respective contributions.
 * The project versioning (Git) records all such contribution source information.
 *                                           
 *                                                                              
 * The BHoM is free software: you can redistribute it and/or modify         
 * it under the terms of the GNU Lesser General Public License as published by  
 * the Free Software Foundation, either version 3.0 of the License, or          
 * (at your option) any later version.                                          
 *                                                                              
 * The BHoM is distributed in the hope that it will be useful,              
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
 * GNU Lesser General Public License for more details.                          
 *                                                                            
 * You should have received a copy of the GNU Lesser General Public License     
 * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
 */

using BH.oM.Structure.Loads;
using Lusas.LPI;
using BH.Engine.Reflection;

namespace BH.Adapter.Lusas
{
#if Debug18 || Release18
    public partial class LusasV18Adapter
#elif Debug19 || Release19
    public partial class LusasV19Adapter
#else
    public partial class LusasV17Adapter
#endif
    {
        /***************************************************/
        /**** Private Methods                           ****/
        /***************************************************/

        private IFLoadcase CreateLoadcase(Loadcase loadcase)
        {
            IFLoadcase lusasLoadcase;

            if (d_LusasData.existsLoadset(loadcase.Name))
            {
                lusasLoadcase = (IFLoadcase)d_LusasData.getLoadset(loadcase.Name);
            }
            else
            {
                if (loadcase.Number == 0)
                {
                    lusasLoadcase = d_LusasData.createLoadcase(loadcase.Name);
                    Compute.RecordWarning($"Loadcase {loadcase.Name} ID will be autogenerated by Lusas.");
                }
                else
                {
                    lusasLoadcase = d_LusasData.createLoadcase(loadcase.Name, "", loadcase.Number);
                }
            }

            loadcase.CustomData[AdapterIdName] = lusasLoadcase.getID();

            return lusasLoadcase;
        }

        /***************************************************/

    }
}
